// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Cogl {

	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.Runtime.InteropServices;

	public partial class Texture {

		protected Texture() : base(IntPtr.Zero)
		{
		}
	}
}
